#!/usr/bin/env node
const yargs = require('yargs');
const path = require('path');
const convert = require('./');

const argv = yargs.command(
  '$0 <input> <output>',
  'Convert a svg file to a svelte component.',
  args => args
    .positional('input', {
      describe: 'svg input file path',
      type: 'string'
    })
    .positional('output', {
      describe: 'svelte output file path',
      type: 'string'
    })
    .option('config', {
      describe: 'svgo config file path',
      default: path.join(__dirname, 'svgo.yml')
    })
    .example('svg2svelte menu.svg IconMenu.svelte')
)
  .help()
  .alias('config', 'c')
  .alias('version', 'v')
  .alias('help', 'h')
  .argv;

convert(argv.input, argv.output, argv.config);
