#!/usr/bin/env node
const yargs = require('yargs');
const path = require('path');
const convert = require('./');

const argv = yargs.command(
  '$0 <input> <output>',
  'Convert a svg file to a svelte component.',
  args => args
    .positional('input', {
      type: 'string',
      describe: 'svg input file path'
    })
    .positional('output', {
      type: 'string',
      describe: 'svelte output file path'
    })
    .option('ts', {
      type: 'boolean',
      describe: 'typescript'
    })
    .option('config', {
      alias: 'c',
      describe: 'svgo config file path',
      default: path.join(__dirname, 'svgo.config.js')
    })
    .example('svg2svelte menu.svg IconMenu.svelte')
)
  .help()
  .argv;

convert(argv.input, argv.output, argv.ts, argv.config);
